cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail_view, name='cart_detail'),
    path('add/<int:product_id>/', views.add_to_cart_view, name='cart_add'),
    path('remove/<int:product_id>/', views.remove_form_cart, name= 'cart_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('products.urls')),
    path('rosetta/', include('rosetta.urls')),
    path('call/', include('pages.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('orders.urls')),
    path('payment/', include('payment.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from . import views

app_name ='orders'

urlpatterns = [
    path('create/', views.order_create_view, name='order_create')
]

cart/forms.py
from django import forms

class AddToCartForm(forms.Form):
    QUANTITY_CHOICES = [(i, str(i))for i in range(1,31)]
    inplace = forms.BooleanField(required=False, widget=forms.HiddenInput)
    quantity = forms.TypedChoiceField(choices=QUANTITY_CHOICES, coerce=int)

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect

from products.models import Product

from .cart import Cart
from .forms import AddToCartForm

def cart_detail_view(request):
    cart = Cart(request)
    for item in cart:
        item['product_update_quantity_form'] = AddToCartForm(
            initial={'quantity':item['quantity'], 'inplace':True}
        )
    return render(request, 'cart/cart_detail.html',{'cart':cart})



def add_to_cart_view(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product,pk = product_id )
    form = AddToCartForm(request.POST)
    if form.is_valid():
        cleaned_data = form.cleaned_data
        quantity = cleaned_data['quantity']
        cart.add(product,quantity, replace_current_quantity=cleaned_data['inplace'] )
        return redirect('cart:cart_detail')
    

def remove_form_cart(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, pk=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

cart/templates/cart/cart_detail.html
{% extends "_base.html" %}
{% load i18n %}
{% load persian_number %}
{% load humanize %}

{% block page_title %}{% trans "cart detail" %}{% endblock page_title %}
{% block content %}

    <!-- Breadcrumb area Start -->
    <div class="breadcrumb-area bg-color ptb--90" data-bg-color="#f6f6f6">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="d-flex justify-content-between align-items-center flex-sm-row flex-column">
                        <h1 class="page-title">{% trans "cart" %}</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb area End -->

    <!-- Main Content Wrapper Start -->
    <div class="main-content-wrapper">
        <div class="page-content-inner ptb--80">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 mb-md--50">
                        <div class="row no-gutters">
                            <div class="col-12">
                                <div class="table-content table-responsive">
                                    <table class="table text-center">
                                        <thead>
                                            <tr>
                                                <th>&nbsp;</th>
                                                <th>{% trans "image product" %}</th>
                                                <th> {% trans "product name" %}</th>
                                                <th>{% trans "price" %}</th>
                                                <th>{% trans "quantity" %}</th>
                                                <th>{% trans "total" %}</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for item in cart %}
                                                <tr>
                                                    <td class="product-remove text-left">
                                                        <a href="{% url "cart:cart_remove" item.product_obj.id %}">
                                                            <i class="flaticon flaticon-cross"></i>
                                                        </a>
                                                        </td>
                                                    <td class="product-thumbnail text-left">
                                                        <img src="{{item.product_obj.image.url}}" >
                                                    </td>
                                                    <td class="product-name wide-column">
                                                        <h3>
                                                            <a href="{{item.product_obj.get_absolute_url}}">{{item.product_obj.title}}</a>
                                                        </h3>
                                                    </td>
                                                    <td class="product-price">
                                                        <span class="product-price-wrapper">
                                                            <span class="money">{{item.product_obj.price|translate|intcomma:False}} {% trans "$" %}</span>
                                                        </span>
                                                    </td>
                                                    <td class="product-quantity">
                                                        <form action="{% url "cart:cart_add" item.product_obj.id %}" method='POST'>
                                                            {% csrf_token %}
                                                            <div class="quantity">
                                                                <input 
                                                                type="number" 
                                                                class="quantity-input" 
                                                                name="quantity" 
                                                                id="qty-1" 
                                                                value="{{item.quantity}}" 
                                                                min="1"
                                                                max='30'
                                                                >
                                                            </div>
                                                            <button type='submit'>update</button>
                                                        {{item.product_update_quantity_form.inplace}}
                                                        <form>
                                                    </td>
                                                    <td class="product-total-price">
                                                        <span class="product-price-wrapper">
                                                            <span class="money">{{item.total_price|translate|intcomma:False}}{% trans "$" %}</span>
                                                        </span>
                                                    </td>
                                                </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>  
                            </div>
                        </div>
                        <div class="row no-gutters border-top pt--20 mt--20">
                            <div class="col-sm-6 text-sm-right">
                                <button type="submit" class="cart-form__btn">{% trans "clear cart" %}</button>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="cart-collaterals">
                            <div class="cart-totals">
                                <h5 class="font-size-14 font-bold mb--15">{% trans "total" %}</h5>
                                <div class="cart-calculator">
                                    <div class="cart-calculator__item order-total">
                                        <div class="cart-calculator__item--head">
                                            <span>{% trans "total" %}</span>
                                        </div>
                                        <div class="cart-calculator__item--value">
                                            <span class="product-price-wrapper">
                                                <span class="money">{{cart.get_total_price|translate|intcomma:False}} {% trans "$" %}</span>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <a href="{% url "orders:order_create" %}" class="btn btn-fullwidth btn-bg-red btn-color-white btn-hover-2">
                                {% trans "checkout" %}
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Main Content Wrapper Start -->



{% endblock content %}

cart/templates/cart/mini_cart.html
{% load i18n %}
<!-- Mini Cart Start -->
<aside class="mini-cart" id="miniCart">
    <div class="mini-cart-wrapper">
        <a href="" class="btn-close"><i class="flaticon flaticon-cross"></i></a>
        <div class="mini-cart-inner">
            <h3 class="mini-cart__heading mb--40 mb-lg--30 text-right">سبد خرید</h3>
            <div class="mini-cart__content">
                <ul class="mini-cart__list text-right">
                    {% for item in cart %}
                        <li class="mini-cart__product d-flex justify-content-between">
                            <div class="mini-cart__product__image">
                                <a href="{{item.prouduct_obj.get_absolute_url}}">
                                    <img src="{{item.product_obj.image.url}}" alt="">
                                </a>
                            </div>
                            <div class="mini-cart__product__content pt-2">
                                <span class="mini-cart__product__title d-flex flex-row justify-content-between">
                                    <a href="#">{{item.product_obj.title}}</a>
                                    <a href="#" class="">
                                        &#10060;
                                    </a>
                                </span>
                                <span class="mini-cart__product__quantity">
                                    <span>{{item.total_price}} {% trans "$" %}</span> &#215; <span>{{item.quantity}}</span>
                                </span>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
                <div class="mini-cart__total">
                    <span>{% trans "total" %}</span>
                    <span class="ammount">{{cart.get_total_price}} {% trans "$" %}</span>
                </div>
                <div class="mini-cart__buttons">
                    <a href="{% url "cart:cart_detail" %}" class="btn btn-fullwidth btn-bg-sand mb--20">{% trans "go to cart" %}</a>
                    <a href="{% url "orders:order_create" %}" class="btn btn-fullwidth btn-bg-sand">{% trans "checkout" %}</a>
                </div>
            </div>
        </div>
    </div>
</aside>
<!-- Mini Cart End -->