accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('verify/', views.UserRegisterCodeView.as_view(), name='verify_code'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail_view, name='cart_detail'),
    path('add/<int:product_id>/', views.add_to_cart_view, name='cart_add'),
    path('remove/<int:product_id>/', views.remove_form_cart, name= 'cart_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('products.urls')),
    path('rosetta/', include('rosetta.urls')),
    path('call/', include('pages.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('orders.urls')),
    path('payment/', include('payment.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from . import views

app_name ='pages'

urlpatterns = [
    path('', views.call_with_us, name='call_us'),
]

products/urls.py
from django.urls import path

from . import views

app_name = 'products'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='product_list'),
    path('product/<int:pk>/', views.product_detail_view, name='product_detail'),
]

templates/Preloader.html
 <!-- Preloader Start -->
<div class="ShoppingYar-preloader active">
    <div class="ShoppingYar-preloader-inner h-100 d-flex align-items-center justify-content-center">
        <div class="ShoppingYar-child ShoppingYar-bounce1"></div>
        <div class="ShoppingYar-child ShoppingYar-bounce2"></div>
        <div class="ShoppingYar-child zuka-bounce3"></div>
    </div>
</div>
<!-- Preloader End --> 

templates/_base.html
<!doctype html>
{% load static %}
{% load i18n %}
<html  class="no-js">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block page_title %}{% endblock page_title %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicons -->
    <link rel="shortcut icon" href="{% static "img/favicon.ico" %}" type="image/x-icon">
    <link rel="apple-touch-icon" href="{% static "img/icon.png" %}">

    <!-- ************************* CSS Files ************************* -->

    <link rel="stylesheet" href="{% static "css/_base.css" %}">

    <!-- Vendor CSS -->
    <link rel="stylesheet" href="{% static "css/vendor.css" %}">

    <!-- style css -->
    <link rel="stylesheet" href="{% static "css/main.css" %}">


</head>

<body dir='rtl'>
    {% include "preloader.html" %}
    <!-- Main Wrapper Start -->
    <div class="wrapper">
        <!-- Header Start -->
        <header class="header">
            <div class="header-inner fixed-header">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-xl-9 col-lg-8 col-5 col-xs-0 col-none col-sm-block p-0">
                            <nav class="main-navigation">
                                <div class="site-branding" style="margin-right: 30px;">
                                    <a href="index.html" class="logo">
                                        <figure class="logo--normal d-none d-sm-block">
                                            <img class="px-5" src="assets/img/codingyar_logo.png" style="max-height: 50px; margin-bottom: -15px;" alt="Logo">
                                        </figure>
                                    </a>
                                </div>
                                <div class="mainmenu-nav d-none d-lg-block w-100 pr-3">
                                    <ul class="mainmenu d-lg-flex jusity-content-end jusity-content-lg-start pt-4">
                                        <li class="mainmenu__item menu-item-has-children active">
                                            <a href="{% url "products:product_list" %}" class="mainmenu__link">
                                                <span class="mm-text">{% trans "product list" %}</span>
                                            </a>
                                        </li>
                                        {% comment %} <li class="mainmenu__item menu-item-has-children">
                                            <a href="Blog.html" class="mainmenu__link">
                                                <span class="mm-text">وبلاگ</span>
                                            </a>
                                        </li> {% endcomment %}
                                        <li class="mainmenu__item menu-item-has-children">
                                            <a href="#" class="mainmenu__link">
                                                <span class="mm-text">صفحات</span>
                                            </a>
                                         </li>
                                        <li class="mainmenu__item">
                                            <a href="{% url "pages:call_us" %}" class="mainmenu__link">
                                                <span class="mm-text">تماس با ما</span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </nav>
                        </div>
                        <div class="col-xl-3 col-lg-4 col-sm-7 col-12 p-0">
                            <ul class="header-toolbar">
                                <li class="header-toolbar__item">
                                    <a href="wishlist.html" class="header-toolbar__btn mx-4">
                                        <i class="flaticon flaticon-like"></i>
                                    </a>
                                </li>
                                <li class="header-toolbar__item mini-cart-item">
                                    <a href="#miniCart" class="header-toolbar__btn toolbar-btn mini-cart-btn">
                                        <i class="flaticon flaticon-shopping-cart"></i>
                                        <sup class="mini-cart-count">2</sup>
                                    </a>
                                </li>
                                <li class="header-toolbar__item user-info">
                                    <a href="my-account.html" class="header-toolbar__btn">
                                        <i class="flaticon flaticon-user"></i>
                                    </a>
                                    <ul class="user-info-menu">
                                        {% if user.is_authenticated %}
                                            <li>

                                                <a class="text-right" href="my-account.html">{% trans "prodfile" %}</a>
                                            </li>
                                            <li>
                                                <form action="{% url 'accounts:logout' %}" method="POST">
                                                    {% csrf_token %}
                                                    <button type="submit" class='btn'>{% trans "log out" %}</button>
                                                </form>
                                            </li>
                                        {% else %}
                                            <li>
                                                <a class="text-right" href="{% url "accounts:login" %}">{% trans "login" %}</a>
                                            </li>
                                            <li>
                                                <a class="text-right" href="{% url "accounts:user_register" %}">{% trans "signup" %}</a>
                                            </li>
                                        {% endif %}
                                    </ul>
                                </li>
                                <li class="header-toolbar__item">
                                    <a href="#searchForm" class="header-toolbar__btn toolbar-btn">
                                        <i class="flaticon flaticon-search"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <div class="mobile-menu"></div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Header End -->

        {% include "messages.html" %}
        {% block content %}
        {% endblock content %}
        {% include "footer.html" %}
        {% include "search.html" %}
        {% include "cart/mini_cart.html" %}


        <!-- Mini Cart Start -->
        <aside class="mini-cart" id="miniCart">
            <div class="mini-cart-wrapper">
                <a href="" class="btn-close"><i class="flaticon flaticon-cross"></i></a>
                <div class="mini-cart-inner">
                    <h3 class="mini-cart__heading mb--40 mb-lg--30 text-right">سبد خرید</h3>
                    <div class="mini-cart__content">
                        <ul class="mini-cart__list text-right">
                            <li class="mini-cart__product d-flex justify-content-between">
                                <div class="mini-cart__product__image">
                                    <a href="#">
                                        <img src="assets/img/products/prod-1-100x100.jpg" alt="products">
                                    </a>
                                </div>
                                <div class="mini-cart__product__content pt-2">
                                    <span class="mini-cart__product__title d-flex flex-row justify-content-between">
                                        <a href="#"> محصول سماره یک </a>
                                        <a href="#" class="">
                                            &#10060;
                                        </a>
                                    </span>
                                    <span class="mini-cart__product__quantity">
                                        <span>۴۹,۰۰۰ تومان</span> &#215; <span>۱</span>
                                    </span>
                                </div>
                            </li>
                            <li class="mini-cart__product d-flex justify-content-between">
                                <div class="mini-cart__product__image">
                                    <a href="#">
                                        <img src="assets/img/products/prod-1-100x100.jpg" alt="products">
                                    </a>
                                </div>
                                <div class="mini-cart__product__content pt-2">
                                    <span class="mini-cart__product__title d-flex flex-row justify-content-between">
                                        <a href="#"> محصول سماره یک </a>
                                        <a href="#" class="">
                                            &#10060;
                                        </a>
                                    </span>
                                    <span class="mini-cart__product__quantity">
                                        <span>۴۹,۰۰۰ تومان</span> &#215; <span>۱</span>
                                    </span>
                                </div>
                            </li>
                            <li class="mini-cart__product d-flex justify-content-between">
                                <div class="mini-cart__product__image">
                                    <a href="#">
                                        <img src="assets/img/products/prod-1-100x100.jpg" alt="products">
                                    </a>
                                </div>
                                <div class="mini-cart__product__content pt-2">
                                    <span class="mini-cart__product__title d-flex flex-row justify-content-between">
                                        <a href="#"> محصول سماره یک </a>
                                        <a href="#" class="">
                                            &#10060;
                                        </a>
                                    </span>
                                    <span class="mini-cart__product__quantity">
                                        <span>۴۹,۰۰۰ تومان</span> &#215; <span>۱</span>
                                    </span>
                                </div>
                            </li>
                        </ul>
                        <div class="mini-cart__total">
                            <span>جمع کل</span>
                            <span class="ammount">۱۴۸,۰۰۰ تومان</span>
                        </div>
                        <div class="mini-cart__buttons">
                            <a href="cart.html" class="btn btn-fullwidth btn-bg-sand mb--20">مشاهده سبد خرید</a>
                            <a href="checkout.html" class="btn btn-fullwidth btn-bg-sand">پرداخت</a>
                        </div>
                    </div>
                </div>
            </div>
        </aside>
        
        <!-- Mini Cart End -->

        <!-- Global Overlay Start -->
        <div class="ShoppingYar-global-overlay"></div>
        <!-- Global Overlay End -->

    </div>
    <!-- Main Wrapper End -->

    <!-- ************************* JS Files ************************* -->

    <!-- jQuery JS -->
    <script src="{% static "js/vendor.js" %}"></script>

    <!-- Main JS -->
    <script src="{% static "js/main.js" %}"></script>

</body>

</html>

templates/footer.html
{% load static %}
{% load i18n %}
<!-- Footer Start-->
<footer class="footer">
    <div class="footer-top bg-color ptb--50" data-bg-color="#f6f6f6">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-9 text-center">
                    <div class="footer-widget mb--50">
                        <div class="textwidget">
                            <img src="assets/img/codingyar_logo.png" alt="Logo">
                        </div>
                    </div>
                    <div class="footer-widget mb--50 pb--1">
                        <ul class="footer-menu">
                            <li><a href="">{% trans "about us" %}</a></li>
                            <li><a href="">{% trans "term and condition" %}</a></li>
                            <li><a href="">{% trans "call with us" %}</a></li>
                        </ul>
                    </div>
                    <div class="footer-widget">
                        Ho3ein770227.ir
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- Footer End-->

templates/messages.html
<style>
    .alert {
        padding: 3px;
        font-size: 15px;
        margin-bottom: 10px
    }
    .custom-div {
        max-width: 300px;
        border-radius: 8px;
    }
</style>
    
{% if messages %}
    <div class='container'>
        {% for message in messages %}
            <div class='custom-div alert alert-{{message.tags}}'>
                {{message}}
            </div>
        {% endfor %}
    </div>
{% endif %}

templates/search.html
{% load i18n %}
<!-- Search form Popup Start -->
<div class="searchform__popup" id="searchForm">
    <a href="#" class="btn-close"><i class="flaticon flaticon-cross"></i></a>
    <div class="searchform__body">
    <p>{% trans "Enter your phrase in the box below" %}</p>
        <form class="searchform">
            <input type="text" name="popup-search" id="popup-search" class="searchform__input" placeholder={% trans "Search among products" %}
            <button type="submit" class="searchform__submit"><i class="flaticon flaticon-magnifying-glass-icon"></i></button>
        </form>
    </div>
</div>
<!-- Search form Popup End -->